name: WordPress CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2, phpcs
      
      - name: Run PHPCS
        uses: shalior/wordpress-phpcs-action@master  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_default_configuration_file: true
          phpcs_args: '-n' # ignore warnings

      - name: Fail on PHPCS
        run: |
          if [ $? -eq 1 ]; then
            exit 1
          fi
          
  build:
        runs-on: ubuntu-latest
        needs: test
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
              
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
              
          - name: Build and push Docker image
            if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature')
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
          
  deploy_to_Production:
                    runs-on: ubuntu-latest
                    needs: build
                    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
                  
                    steps:
                      - name: Deploy to staging
                        run: echo "Deploying to Production environment"
                          
  deploy_to_test:
              runs-on: ubuntu-latest
              needs: build
              if: startsWith(github.ref, 'refs/heads/feature') && github.event_name == 'push'
                  
              steps:
                - name: Deploy to test environment
                  run: echo "Deploying to test environment"

